### ISSUE TITLE
关于内存和速度的问题

### ISSUE THREAD

**Issue by my-hello-world** [liaopeiyuan/ml-arsenal-public#3]
你好，感谢你的开源。
我只有12G的tesla40,想请问下您下面的代码大概运行内存是多少呢？速度怎么样啊？
se_resnet34，
Unet50_scSE_hyper
SEResnextUnet50_OC_scSE_hyper
而且，您没有说Unet50_scSE_hyper的精度(或许我没看到？)，请问大概多少呢？

**Comment by liaopeiyuan** [comment]
1. Unet50 is deprecated in favor of the object context module, so we didn't retain any experimental results. You are always welcome to try it out on your own!
2. SE_Resnet34 I believe takes around 13 GB VRAM with the setting used in the competition, and SEResnextUnet50_OC_scSE_hyper takes around 25 GB VRAM. Using mixed-precision, multi-gpu training (you may wanna consider using groupnorm/layernorm) and decreasing batch size/input size can greatly reduce that number, as the overhead is mainly on the input size.
